### ISSUE TITLE
Take input image as condition.

### ISSUE THREAD

**Issue by Adenialzz** [dvlab-research/MGM#100]
Can we consider to also take the input image as condition (with e.g. ip-adapter) to realize personalized image generation ?

**Comment by JulianJuaner** [comment]
Hi, we've test to add an input image condition using the IP-Adapter-Plus (SDXL version). Following are some results and discussions.
<img width="926" alt="Screenshot 2024-04-29 at 12 57 22 AM" src="https://github.com/dvlab-research/MGM/assets/37148692/7bf69bd0-2652-40da-87f3-73727d6c68c2">

In general, IPAdapter does have a style and content preservation, but we find it hard to adjust the guidance strengths of different conditions (text & input-image) case-wisely.

**Comment by Adenialzz** [comment]
Indeed, I have encountered the similar problem in practice. The result makes sense. Thanks for your reply and your case. Nice work.
