### ISSUE TITLE
Error while loading model with transformers library

### ISSUE THREAD

**Issue by PrateekPal641** [dvlab-research/MGM#105]
Traceback (most recent call last):
  File "/mnt/nvme/MGM/predict.py", line 161, in <module>
    predictor.setup()
  File "/mnt/nvme/MGM/predict.py", line 85, in setup
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("liuhaotian/llava-v1.5-13b", model_name="llava-v1.5-13b", model_base=None, load_8bit=False, load_4bit=False)
  File "/mnt/nvme/MGM/mgm/model/builder.py", line 97, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/mnt/nvme/miniconda3/envs/mgm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, MGMConfig, MGMConfig, MGMConfig, MGMConfig.

**Comment by yanwei-li** [comment]
Hi, please provide more details to locate the error, like the detailed script and settings for evaluation.

**Comment by raccoon641** [comment]
I tried to load model via autocasual library of huggingface because mgmforcausalmodel is not added in hugging face library.
I managed to load the model via this github repo.

**Comment by Divyanshsingh1910** [comment]
hey @PrateekPal641 could you please help me in loading the mistral model via this repo. Basically I want to access the hidden states of the language model as this code would do if model was on HF
`output = model(**inputs,output_hidden_states = True)`

But since this model is not added on HF, I am finding it a bit harder to do this. Could you please help me here?
