### ISSUE TITLE
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 3, 336, 336]

### ISSUE THREAD

**Issue by baozounan** [dvlab-research/MGM#40]
When I generate it using the example image, it tells me that the dimensions are not correct
![image](https://github.com/dvlab-research/MiniGemini/assets/49280446/7e1bf4df-e980-4cf7-a341-2f013d4c85ce)
![image](https://github.com/dvlab-research/MiniGemini/assets/49280446/85ead11f-933c-40da-82e6-2b709bd440f7)

**Comment by wcy1122** [comment]
Hi, the bug is fixed. You can update the latest code and try again.

**Comment by TGLTommy** [comment]
> Hi, the bug is fixed. You can update the latest code and try again.

Hi, where is the code did you updated ?

**Comment by plf1996** [comment]
> Hi, the bug is fixed. You can update the latest code and try again.

Thank you, I will keep trying
