### ISSUE TITLE
关于代码实现的疑问

### ISSUE THREAD

**Issue by hhaAndroid** [dvlab-research/MGM#43]
作者好，非常感谢你的开源。我有两个疑问想咨询下

**1. convnext 的 drop path 问题**

convnext 的 drop path 是 0.1，虽然你在训练时候设置的是不训练，但是这个路径还是会执行的。原则上在训练时候，convnext 要设置为 eval 模式吧？ 我没有找到相关代码，有点奇怪，想了解下

**2. 代码鲁棒性问题**

如果是 clip+convnext 组合方式训练没有任何问题。但是我想尝试 siglip，发现在仅仅将 clip 换成 siglip 后(均值和方差也是两套)，模型在 iter=2 时候就会出现 nan。注释如下

```
        # token attention
        embed_query = self.vlm_uni_query_projector(images)
        embed_aux = self.vlm_uni_aux_projector(images_aux)
        embed_value = self.vlm_uni_val_projector(images_aux)
        # TODO siglip+convnext 在第一次 forward 后正常，但是 embed_att 会出现 nan
        # TODO 导致第二次迭代时候 embed_value 会出现 nan，无法训练
        # TODO 怀疑是特征不匹配，即使全部转换为 fp32 也会出现 nan, 需要进一步排查
        embed_att = embed_query[:, :, None] @ (embed_aux.transpose(-1, -2) / (embed_aux.shape[-1] ** 0.5))
        # print('=xxxx=', torch.any(torch.isnan(embed_query)).item(),
        #       torch.any(torch.isnan(embed_aux)).item(),
        #       torch.any(torch.isnan(embed_value)).item(),
        #       torch.any(torch.isnan(embed_att)).item())
        embed_att = embed_att.nan_to_num()
        embed_feat = (embed_att.softmax(-1) @ embed_value).mean(2)
        # print('=xxcccxx=', torch.any(torch.isnan(embed_feat)).item())
        image_features = images + embed_feat
        return image_features
```

不知道作者对于这个问题是咋看的。有一个细节不一样：因为 siglip 输入是 384x384 的，输出尺度是 27x27，所以我必须要将 convnext 输入分辨率设置为 864, 这样才可以保证两者空间完全对齐。

期待您的回复。

**Comment by yanwei-li** [comment]
Hi, Thanks for your interest in our work. The responses are given as follows:
1. Thanks for your report. We keep the drop path rate during training to maintain the original ConvNext training manner. We will try to drop this during training.
2. Is the ViT-based model used with Siglip? It could be strange with the input size 384 and outsize 27 in ViT setting.

**Comment by hhaAndroid** [comment]
@yanwei-li  the slglip is here https://huggingface.co/google/siglip-so400m-patch14-384. Performance is much better than clip, and we have also verified it in our experiments, so we would like to give it a try.

**Comment by lucasjinreal** [comment]
Siglip preprocessing mean and std far different from openai clip....

**Comment by hhaAndroid** [comment]
@lucasjinreal  Would this have a significant impact? I understand that as long as the distribution of the feature outputs is consistent, it doesn't actually have any relation to the mean and variance.

**Comment by yanwei-li** [comment]
@hhaAndroid Thanks for pointing out the drop path issue. I tried to train without drop path and it got better results in better performance with 7B model in TextVQA (65.2->65.9), MME(1523/316->1540/332), and MM-Vet(40.8->42.1). So, we update the code to support training without the drop path [here](https://github.com/dvlab-research/MiniGemini/blob/main/scripts/llama/train/stage_1_2_full_v7b_336_hr_768_nodp.sh).
