### ISSUE TITLE
怎么从你们的检查点启动呢

### ISSUE THREAD

**Issue by HongLouyemeng** [dvlab-research/MGM#45]
我发现教程只有从开源大模型的权重微调的，如果要在你们的检查点启动使用什么方法呢

**Comment by yanwei-li** [comment]
Hi, I'm not sure what's the meaning of "start from checkpoint". Did you mean continue training from the pre-trained checkpoint?

**Comment by HongLouyemeng** [comment]
> Hi, I'm not sure what's the meaning of "start from checkpoint". Did you mean continue training from the pre-trained checkpoint?

Hi,没错QAQ 我可能不太专业哈

**Comment by HongLouyemeng** [comment]
> 同问

我估摸着是这样，还是等作者回答把

**Comment by zhiting-wang** [comment]
I have the same question. Could author write a document to explain it?

**Comment by GoldenFishes** [comment]
`
from minigemini.model.builder import load_pretrained_model
# loal Mini-Gemini-2B
tokenizer, model, image_processor, context_len = load_pretrained_model(model_path="work_dirs/Mini-Gemini-2B",
                                                                       model_base=None, model_name='YanweiLi/Mini-Gemini-2B',
                                                                       load_8bit=False, load_4bit=False,
                                                                       device_map="auto", device="cuda",
                                                                       use_flash_attn=False)
`

**Comment by HongLouyemeng** [comment]
> ` from minigemini.model.builder import load_pretrained_model
> 
> # loal Mini-Gemini-2B
> tokenizer, model, image_processor, context_len = load_pretrained_model(model_path="work_dirs/Mini-Gemini-2B", model_base=None, model_name='YanweiLi/Mini-Gemini-2B', load_8bit=False, load_4bit=False, device_map="auto", device="cuda", use_flash_attn=False) `

https://huggingface.co/YanweiLi/Mini-Gemini-8x7B/blob/main/config.json
        elif "mixtral" in model_args.model_name_or_path:

**Comment by yanwei-li** [comment]
Hi, I guess you can try this 
```
FINETUNE_NAME=Mini-Gemini-7B
STAGE3_NAME=Your_prefer_name
AUX_SIZE=768
deepspeed minigemini/train/train_mem.py \
    --deepspeed ./scripts/zero2_offload.json \
    --model_name_or_path ./work_dirs/$FINETUNE_NAME \
    --version v1 \
    --data_path ./data/MiniGemini-Finetune/minigemini_instruction.json \
    --image_folder ./data/MiniGemini-Finetune \
    --vision_tower model_zoo/OpenAI/clip-vit-large-patch14-336 \
    --vision_tower_aux model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --image_size_aux $AUX_SIZE \
    --bf16 True \
    --output_dir ./work_dirs/$STAGE3_NAME \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

**Comment by xylcbd** [comment]
> Hi, I guess you can try this
> 
> ```
> FINETUNE_NAME=Mini-Gemini-7B
> STAGE3_NAME=Your_prefer_name
> AUX_SIZE=768
> deepspeed minigemini/train/train_mem.py \
>     --deepspeed ./scripts/zero2_offload.json \
>     --model_name_or_path ./work_dirs/$FINETUNE_NAME \
>     --version v1 \
>     --data_path ./data/MiniGemini-Finetune/minigemini_instruction.json \
>     --image_folder ./data/MiniGemini-Finetune \
>     --vision_tower model_zoo/OpenAI/clip-vit-large-patch14-336 \
>     --vision_tower_aux model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup \
>     --mm_projector_type mlp2x_gelu \
>     --mm_vision_select_layer -2 \
>     --mm_use_im_start_end False \
>     --mm_use_im_patch_token False \
>     --image_aspect_ratio pad \
>     --group_by_modality_length True \
>     --image_size_aux $AUX_SIZE \
>     --bf16 True \
>     --output_dir ./work_dirs/$STAGE3_NAME \
>     --num_train_epochs 1 \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 2 \
>     --evaluation_strategy "no" \
>     --save_strategy "steps" \
>     --save_steps 1000 \
>     --save_total_limit 1 \
>     --learning_rate 2e-5 \
>     --weight_decay 0. \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 True \
>     --model_max_length 2048 \
>     --gradient_checkpointing True \
>     --dataloader_num_workers 4 \
>     --lazy_preprocess True \
>     --report_to wandb
> ```

按照这个操作，报以下warning，正常吗？我看代码是在做MiniGeminiLlamaForCausalLM.from_trained加载时并不会加载vision_tower和vision_tower_aux的权重，而是在后续从clip/openclip重新加载的权重，那不就与你们预训练好的MiniGeminiLlamaForCausalLM中的vision_tower、vision_tower_aux的权重不一致了吗？（当然，如果你们没有微调过vision_tower、vision_tower_aux的话应该也没问题，但感觉不是很规范，为什么不在MiniGeminiLlamaForCausalLM.from_trained一起加载权重呢）
```
Some weights of the model checkpoint at model_zoo/YanweiLi/Mini-Gemini-34B-HD were not used when initializing MiniGeminiLlamaForCausalLM: ['model.vision_tower.vision_tower.vision_model.embeddings.class_embedding', 'model.vision_tower.vision_tower.vision_model.embeddings.patch_embedding.weight
```

**Comment by HongLouyemeng** [comment]
> > Hi, I guess you can try this
> > ```
> > FINETUNE_NAME=Mini-Gemini-7B
> > STAGE3_NAME=Your_prefer_name
> > AUX_SIZE=768
> > deepspeed minigemini/train/train_mem.py \
> >     --deepspeed ./scripts/zero2_offload.json \
> >     --model_name_or_path ./work_dirs/$FINETUNE_NAME \
> >     --version v1 \
> >     --data_path ./data/MiniGemini-Finetune/minigemini_instruction.json \
> >     --image_folder ./data/MiniGemini-Finetune \
> >     --vision_tower model_zoo/OpenAI/clip-vit-large-patch14-336 \
> >     --vision_tower_aux model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup \
> >     --mm_projector_type mlp2x_gelu \
> >     --mm_vision_select_layer -2 \
> >     --mm_use_im_start_end False \
> >     --mm_use_im_patch_token False \
> >     --image_aspect_ratio pad \
> >     --group_by_modality_length True \
> >     --image_size_aux $AUX_SIZE \
> >     --bf16 True \
> >     --output_dir ./work_dirs/$STAGE3_NAME \
> >     --num_train_epochs 1 \
> >     --per_device_train_batch_size 8 \
> >     --per_device_eval_batch_size 4 \
> >     --gradient_accumulation_steps 2 \
> >     --evaluation_strategy "no" \
> >     --save_strategy "steps" \
> >     --save_steps 1000 \
> >     --save_total_limit 1 \
> >     --learning_rate 2e-5 \
> >     --weight_decay 0. \
> >     --warmup_ratio 0.03 \
> >     --lr_scheduler_type "cosine" \
> >     --logging_steps 1 \
> >     --tf32 True \
> >     --model_max_length 2048 \
> >     --gradient_checkpointing True \
> >     --dataloader_num_workers 4 \
> >     --lazy_preprocess True \
> >     --report_to wandb
> > ```
> 
> Following this operation, the following warning is reported. Is this normal? I see that the code does not load the weights of vision_tower and vision_tower_aux when loading MiniGeminiLlamaForCausalLM.from_trained, but the weights are reloaded from clip/openclip later. Isn’t that the same as the weights of vision_tower and vision_tower_aux in your pre-trained MiniGeminiLlamaForCausalLM? Are the weights inconsistent? (Of course, if you haven’t fine-tuned vision_tower and vision_tower_aux, it should be fine, but it doesn’t feel very standardized. Why not load the weights together with MiniGeminiLlamaForCausalLM.from_trained)
> 
> ```
> Some weights of the model checkpoint at model_zoo/YanweiLi/Mini-Gemini-34B-HD were not used when initializing MiniGeminiLlamaForCausalLM: ['model.vision_tower.vision_tower.vision_model.embeddings.class_embedding', 'model.vision_tower.vision_tower.vision_model.embeddings.patch_embedding.weight
> ```

这个问题可以哦

**Comment by Erickrus** [comment]
请问有谁把finetuning 流程跑完了 ?

**Comment by a2382625920** [comment]
同问，有没有把微调的全部流程全部完成的

**Comment by a2382625920** [comment]
微调这么吓人吗？，虽然推理单张A100就足够了，内存小点只有60G

**Comment by HongLouyemeng** [comment]
单节点删除hostfile，我怀疑是zero2不行导致异构内存没利用好

**Comment by HongLouyemeng** [comment]
问题解决了。
