### ISSUE TITLE
minigemini_instruction.json包含了预训练的LLaVA Images，但是在readme中没有写到微调用到了这部分数据

### ISSUE THREAD

**Issue by shidingz** [dvlab-research/MGM#50]
minigemini_instruction.json中有条目的image为llava/LLaVA-Pretrain/images/00013/000133305.jpg，有很多llava的图片，但是readme中没有提到要用llava的图片，是你们疏忽了吗

**Comment by yanwei-li** [comment]
Hi, this is attributed to that the adopted [ShareGPT4V-100K](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V) uses the LLaVA-Pretrain images for captions. We fix the data path in README. You can directly put the [LLaVA Images](https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain) to `data/MiniGemini-Finetune/llava/LLaVA-Pretrain/images`.
