### ISSUE TITLE
About vl model path

### ISSUE THREAD

**Issue by AllentDan** [dvlab-research/MGM#51]
`model_zoo/OpenAI/clip-vit-large-patch14-336` and `model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup` from https://huggingface.co/YanweiLi/Mini-Gemini-7B/blob/main/config.json#L31

What is the exact model path of the huggingface?

**Comment by lightingvector** [comment]
openai/clip-vit-large-patch14-336
laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup

**Comment by yanwei-li** [comment]
Hi, please find them here [CLIP-Vit-L-336](https://huggingface.co/openai/clip-vit-large-patch14-336), [OpenCLIP-ConvNeXt-L](https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup)
