### ISSUE TITLE
Feature Request: llama.cpp support

### ISSUE THREAD

**Issue by deutschthomas** [dvlab-research/MGM#52]
I have an interest in this project, but my system VRAM is small so I prefer to use the [llama.cpp](https://github.com/ggerganov/llama.cpp)-based toolchain(ollama etc.) and GGUF quantization. However, the dual encoder architecture of the model may cause a necessary change of the existing [LLaVA workflow](https://github.com/ggerganov/llama.cpp/tree/master/examples/llava) to be used with this model and the support of multimodal Gemma isn't implemented yet. Do you have any idea? This will benefit the devices with small (v)RAMs to use this model.

**Comment by yanwei-li** [comment]
Thanks for your suggestion! We do not have enough bandwidth now. But we will try to implement it. Thanks.
