### ISSUE TITLE
Regarding license for using the models

### ISSUE THREAD

**Issue by thiner** [dvlab-research/MGM#56]
I noticed that the code is licensed under Apache 2.0, but the dataset and checkpoints are licensed under CC-NC-4.0. As per my understanding, the license forbid usage of the dataset to train a new model and then sell it to third-party. But what if I use the trained model without further training or finetuning in a company project(for internal use only)? Is this legal?

**Comment by yanwei-li** [comment]
Hi, thanks for your interest in our work! Because we build the repo based on LLaVA, we just keep the same license. As for the  internal use, I guess it's better to turn to the legal department in your company to avoid risk.
