### ISSUE TITLE
For multi image

### ISSUE THREAD

**Issue by ZhangScream** [dvlab-research/MGM#58]
In MiniGemini/minigemini/serve/cli.py
I find that     parser.add_argument("--image-file", type=str, default=None) # file_0.jpg,file_1.jpg for multi image,
Does this mean it can support processing multiple images at once?
But i got error that 
    raw_image = image_tensor.reshape(3, 
RuntimeError: shape '[3, 2, 336, 2, 336]' is invalid for input of size 2709504

**Comment by yanwei-li** [comment]
Hi, it actually can support multi-image training and inference, and you can try to modify the code to support this function. I'm not sure whether we will recently support this function officially.
