### ISSUE TITLE
加载模型时卡住了

### ISSUE THREAD

**Issue by kimi360** [dvlab-research/MGM#77]
日志如下：
[model_worker_391073.log](https://github.com/dvlab-research/MiniGemini/files/15035427/model_worker_391073.log)

现象是worker不再输出日志，gradio web模型的地方也没加载出来。Ctrl+c或者kill都无法结束进程

**Comment by wcy1122** [comment]
Hello, thanks for your interest.
It's weird, according to the log, looks like you have not loaded the whole Mini-Gemini model.
I guess it's some memory or cpu issue? Maybe you can use `kill -9` to delete the process.

**Comment by kimi360** [comment]
> Hello, thanks for your interest. It's weird, according to the log, looks like you have not loaded the whole Mini-Gemini model. I guess it's some memory or cpu issue? Maybe you can use `kill -9` to delete the process.

kill -9 也无法结束，只能重启主机

~~~bash
(base) [root@gpt ~]# ps aux | grep 12727 | grep -v grep
root       12727 98.5 19.1 33528484 6215744 pts/1 R+  14:37  70:12 python -m minigemini.serve.cli --model-path work_dirs/Mini-Gemini/Mini-Gemini-2B --image-file test.jpg
(base) [root@gpt ~]# kill -9 12727
(base) [root@gpt ~]# ps aux | grep 12727 | grep -v grep
root       12727 98.5 19.1 33528484 6215744 pts/1 R+  14:37  70:22 python -m minigemini.serve.cli --model-path work_dirs/Mini-Gemini/Mini-Gemini-2B --image-file test.jpg
(base) [root@gpt ~]# 
~~~

**Comment by kimi360** [comment]
已解决，国内网络问题，卡在huggingface下载上了
