### ISSUE TITLE
pretrain error: lack of preprocessor_config.json

### ISSUE THREAD

**Issue by jiezhangGt** [dvlab-research/MGM#92]
--vision_tower ${ROOT_DIR}/model_zoo/OpenAI/clip-vit-large-patch14-336 \
  --vision_tower_aux ${ROOT_DIR}/model_zoo/OpenAI/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup \

where CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup is download from https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup

The error is : 

OSError: ./MGM/model_zoo/OpenAI/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup does not appear to have a file named preprocessor_config.json.

**Comment by berry-ding** [comment]
hi i want to know where i can download the preprocessor_config.json
