### ISSUE TITLE
使用cli调用自定义微调模型，出现'OpenCLIPVisionTower' object has no attribute 'device'

### ISSUE THREAD

**Issue by HongLouyemeng** [dvlab-research/MGM#93]
有老哥知道是啥问题吗

**Comment by shiwk20** [comment]
hi, I encountered the same issue when I inference the model, have you solved it?

**Comment by HongLouyemeng** [comment]
还没有，我换了7B的模型 一样报错。 同学有解决方法及时沟通哦

**Comment by shiwk20** [comment]
好的~

**Comment by shiwk20** [comment]
同学那你把这个issue open以便能被作者关注解答？

**Comment by shiwk20** [comment]
I found the reason. You should put 'mgm' in your model name. This issue is similar to the LLaVa repo, but I forgot it:)

**Comment by HongLouyemeng** [comment]
> I found the reason. You should put 'mgm' in your model name. This issue is similar to the LLaVa repo, but I forgot it:)

是文件名还是config.json呢 同学

**Comment by shiwk20** [comment]
就是你模型取的名字，文件夹重命名就行了

**Comment by HongLouyemeng** [comment]
> I found the reason. You should put 'mgm' in your model name. This issue is similar to the LLaVa repo, but I forgot it:)

+1

**Comment by HongLouyemeng** [comment]
谢谢同学

**Comment by l1019008146** [comment]
hello ,这个问题怎么解决的？ 我也碰到这个问题了

**Comment by l1019008146** [comment]
抱歉，麻烦问下你指得是哪个文件名加mgm？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月26日(周五) 晚上10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dvlab-research/MGM] 使用cli调用自定义微调模型，出现'OpenCLIPVisionTower' object has no attribute 'device' (Issue #93)




  
I found the reason. You should put 'mgm' in your model name. This issue is similar to the LLaVa repo, but I forgot it:)
  
文件名加上mgm就行

**Comment by shiwk20** [comment]
你训练的时候是不是要把ckpt保存到一个文件夹，就这个文件夹的名字

**Comment by l1019008146** [comment]
不是训练模型的时候，是跑源代码中的给的模型的时候报这个错，而且是推理过程
![image](https://github.com/dvlab-research/MGM/assets/41235413/4e7bec22-3192-4299-91ac-3d4e4fc39bc4)

**Comment by shiwk20** [comment]
> 不是训练模型的时候，是跑源代码中的给的模型的时候报这个错，而且是推理过程 ![image](https://private-user-images.githubusercontent.com/41235413/326164905-4e7bec22-3192-4299-91ac-3d4e4fc39bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjYxMjksIm5iZiI6MTcxNDIyNTgyOSwicGF0aCI6Ii80MTIzNTQxMy8zMjYxNjQ5MDUtNGU3YmVjMjItMzE5Mi00Mjk5LTkxYWMtM2Q0ZTRmYzM5YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYzkxMzRkNzY2NGQ2N2MzNjdlZTA0MzcyZjljMGIxOWUxNDAxYmFkMzhjY2QzZWRkODZkYjM2OGNiN2JkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.851z4vLoiFtzprxw8e9yqaKanG47necCLhgspFxWeWc)

我也是推理时候报的错，我的意思是，推理的时候你load的模型不是有路径吗，就这个路径中包含的模型的名字，里面必须要包含mgm。我用的是自己训的模型，所以没包含mgm报了这个错，但如果你用的官方提供的模型，里面本来就包含了mgm却仍然报这个错，那就不知道原因了

**Comment by l1019008146** [comment]
> > 不是训练模型的时候，是跑源代码中的给的模型的时候报这个错，而且是推理过程 ![image](https://private-user-images.githubusercontent.com/41235413/326164905-4e7bec22-3192-4299-91ac-3d4e4fc39bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjYxMjksIm5iZiI6MTcxNDIyNTgyOSwicGF0aCI6Ii80MTIzNTQxMy8zMjYxNjQ5MDUtNGU3YmVjMjItMzE5Mi00Mjk5LTkxYWMtM2Q0ZTRmYzM5YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYzkxMzRkNzY2NGQ2N2MzNjdlZTA0MzcyZjljMGIxOWUxNDAxYmFkMzhjY2QzZWRkODZkYjM2OGNiN2JkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.851z4vLoiFtzprxw8e9yqaKanG47necCLhgspFxWeWc)
> 
> 我也是推理时候报的错，我的意思是，推理的时候你load的模型不是有路径吗，就这个路径中包含的模型的名字，里面必须要包含mgm。我用的是自己训的模型，所以没包含mgm报了这个错，但如果你用的官方提供的模型，里面本来就包含了mgm却仍然报这个错，那就不知道原因了

谢谢你，解决了，是你这个思路

**Comment by ALR-alr** [comment]
> > 不是训练模型的时候，是跑源代码中的给的模型的时候报这个错，而且是推理过程 ![image](https://private-user-images.githubusercontent.com/41235413/326164905-4e7bec22-3192-4299-91ac-3d4e4fc39bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjYxMjksIm5iZiI6MTcxNDIyNTgyOSwicGF0aCI6Ii80MTIzNTQxMy8zMjYxNjQ5MDUtNGU3YmVjMjItMzE5Mi00Mjk5LTkxYWMtM2Q0ZTRmYzM5YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYzkxMzRkNzY2NGQ2N2MzNjdlZTA0MzcyZjljMGIxOWUxNDAxYmFkMzhjY2QzZWRkODZkYjM2OGNiN2JkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.851z4vLoiFtzprxw8e9yqaKanG47necCLhgspFxWeWc)
> 
> 我也是推理时候报的错，我的意思是，推理的时候你load的模型不是有路径吗，就这个路径中包含的模型的名字，里面必须要包含mgm。我用的是自己训的模型，所以没包含mgm报了这个错，但如果你用的官方提供的模型，里面本来就包含了mgm却仍然报这个错，那就不知道原因了

我用的官方的MGM-2B，有这个问题。。。
