### ISSUE TITLE
Excessive Length of Responses from Mini Gemini

### ISSUE THREAD

**Issue by Dopplenum** [dvlab-research/MGM#97]
Description:
I've noticed that when interacting with Mini Gemini, the responses tend to be overly long. While the responses contain valuable information, they often include more details than necessary, making it challenging to quickly grasp the main points.

Expected Behavior:
I expect Mini Gemini to provide concise and relevant responses to my queries, focusing on the essential information without unnecessary elaboration.

Actual Behavior:
Currently, the responses from Mini Gemini tend to be verbose, containing additional details that may not always be directly related to the specific query.

Steps to Reproduce:
1.  Interact with Mini Gemini by asking questions or giving commands.
2. Observe the length and detail of the responses provided.

Impact:
. Long responses make it difficult to quickly extract the required information.
. Reading through lengthy responses can be time-consuming, especially when seeking quick answers or instructions.
. The excessive verbosity may deter users from engaging with Mini Gemini for certain queries or tasks.
Suggestions for Improvement:
1. Implement a summarization feature to provide concise summaries of long responses.
2. Offer options for users to specify the level of detail they prefer in responses.
4. Optimize responses to focus on the most relevant information based on the context of the query.
5. Provide prompts or guidance to encourage users to ask more specific questions, leading to more targeted responses.

Additional Information:
While detailed responses can be beneficial, it's crucial to strike a balance between thoroughness and readability to enhance the user experience.
Introducing features that allow users to customize or tailor responses to their preferences could improve the overall usability and effectiveness of Mini Gemini.

**Comment by yanwei-li** [comment]
Thanks for your detailed suggestion! It's really a good idea. We will try them to make the project better.
